<?php
/**
    100 => 'Continue',  
    101 => 'Switching Protocols',  
    200 => 'OK',
    201 => 'Created',  
    202 => 'Accepted',  
    203 => 'Non-Authoritative Information',  
    204 => 'No Data Found',  
    205 => 'Reset Content',  
    206 => 'Partial Content',  
    300 => 'Multiple Choices',  
    301 => 'Moved Permanently',  
    302 => 'Found',  
    303 => 'See Other',  
    304 => 'Not Modified',  
    305 => 'Use Proxy',  
    306 => '(Unused)',  
    307 => 'Temporary Redirect',  
    400 => 'Required Parameter Missing', 
    401 => 'Unauthorized',  
    402 => 'Payment Required',  
    403 => 'Forbidden',  
    404 => 'Not Found',  
    405 => 'Invalid HTTP Request Method',  
    406 => 'Not Acceptable',  
    407 => 'Proxy Authentication Required',  
    408 => 'Request Timeout',  
    409 => 'Conflict',  
    410 => 'Gone',  
    411 => 'Length Required',  
    412 => 'Precondition Failed',  
    413 => 'Request Entity Too Large',  
    414 => 'Request-URI Too Long',  
    415 => 'Unsupported Media Type',  
    416 => 'Requested Range Not Satisfiable',  
    417 => 'Expectation Failed',  
    500 => 'Internal Server Error',  
    501 => 'Not Implemented',  
    502 => 'Bad Gateway',  
    503 => 'Service Unavailable',  
    504 => 'Gateway Timeout',  
    505 => 'HTTP Version Not Supported'
*/

return array(
    'success'               => array('200' => 'OK'),
    'no_content'            => array('204' => 'No Data Found'),
    'accepted'              => array('204' => 'Request being processed'),
    'save_failure'          => array('204'  => 'Unable to save your data'),
    'duplicate_email'       => array('204'  => 'Email address already exists'),
    'not_modified'          => array('304' => 'No changes found to save Transaction'),
    'required'              => array('400' => 'Required Parameter Missing'),
    'required_value'        => array('400' => 'Required Parameter Value Missing'),
    'max_length'            => array('400' => 'Maximum Length Required'),
    'min_length'            => array('400' => 'Minimum Length Required'),
    'integer'               => array('400' => ':attribute field must be an integer'),
    'float'                 => array('400' => ':attribute field must be a float'),     
    'numeric'               => array('400' => ':attribute field must be numeric'),
    'email'                 => array('400' => 'This is not a valid email address'),
    'alpha'                 => array('400' => ':attribute field must be an alpha value'),
    'alpha_numeric'         => array('400' => ':attribute field must be an alpha value'),
    'forbidden'             => array('403' => 'Forbidden'),
    'method_not_allowed'    => array('405' => 'Invalid HTTP Request Method'),
    'to_long'               => array('413' => 'Request Entity Too Large'),
    'internal_server_err'   => array('500' => 'Internal Server Error'),
);